version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)
    GITHUB_TOKEN:
        secure: 5dFninlYVqNF98Pk9ykQwPU2pBFeQmbMOiFG2iSkg+hhcwF3UfmnDB07lvOwYtez
    NUGET_API_KEY:
        secure: ynOI8xETJ5V28b5ij2huIKbWRvqJU8QtLtFf8FLTJCWbxmcVP/OPpcF4B8jcOOKW

build_script:
- cmd: build.cmd

on_failure:
  - ps: $root = (Resolve-Path artifacts); [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName failed-build }

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*

deploy_script:
    - ps: .\tools\deploy.ps1
