version: '{build}'

pull_requests:
  do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)

build_script:
    - cmd: build.cmd

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*
