version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)
    GITHUB_TOKEN:
        secure: 5dFninlYVqNF98Pk9ykQwPU2pBFeQmbMOiFG2iSkg+hhcwF3UfmnDB07lvOwYtez
    NUGET_API_KEY:
        secure: COpoeqj1SAECW663nwrEcZr3bIqAryNuYZ+tv1uaFgoxhXQw+GEQyYDQXrRvXWkR

build_script:
- cmd: build.cmd

on_failure:
  - ps: $root = (Resolve-Path artifacts); [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName failed-build }

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*

deploy_script:
    - cmd: tools\deploy.cmd
