site_name: FakeItEasy Analyzers
site_dir: artifacts/docs
theme: readthedocs
repo_url: https://github.com/FakeItEasy/FakeItEasy.Analyzers
extra_css: [css/extra-highlight.css]

pages:
- FakeItEasy Analyzer: index.md