site_name: FakeItEasy Analyzers
site_dir: artifacts/docs
theme: readthedocs
repo_url: https://github.com/FakeItEasy/FakeItEasy.Analyzers
extra_css: [css/extra-highlight.css]

nav:
- FakeItEasy Analyzer: index.md

markdown_extensions:
  - pymdownx.tilde