name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: true
        description: "Dry run (doesn't actually publish anything)"

jobs:

  build:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: build
    uses: FakeItEasy/FakeItEasy.Tools/.github/workflows/deploy.yml@43ce14581503ed404628fe66b2b87803c213e050
    with:
      artifact-name: windows-artifacts
      docs-output-prefix: "docs/analyzers"
      dry-run: ${{ github.event.inputs.dry-run == true }}
    secrets: inherit
