name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: true
        description: "Dry run (doesn't actually publish anything)"

jobs:

  build:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: build
    uses: FakeItEasy/FakeItEasy.Tools/.github/workflows/deploy.yml@72f1aa014c808ac3ee72fbb232358b8e71519331
    with:
      artifact-name: windows-artifacts
      docs-output-prefix: "docs/analyzers"
      dry-run: ${{ github.event.inputs.dry-run == true }}
    secrets: inherit
