name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: true
        description: "Dry run (doesn't actually publish anything)"

jobs:

  build:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: ./tools-shared/.github/actions/deploy
      with:
        artifact-name: windows-artifacts
        docs-output-prefix: "docs/analyzers"
        dry-run: ${{ github.event.inputs.dry-run || false }}
